import { Stock } from '../models/stock.model';

export const TOP_TECH_STOCKS: Stock[] = [
  {
    symbol: 'AAPL',
    name: 'Apple Inc.',
    price: 175.0,
    change: 1.5,
    changePercentage: 0.86,
    marketCap: '2.8T',
    volume: '80M',
    avgVolume: '100M',
    peRatio: 30.0,
    dividendYield: 0.5,
  },
  {
    symbol: 'MSFT',
    name: 'Microsoft Corp.',
    price: 300.0,
    change: -2.0,
    changePercentage: -0.66,
    marketCap: '2.5T',
    volume: '50M',
    avgVolume: '60M',
    peRatio: 35.0,
    dividendYield: 0.8,
  },
  {
    symbol: 'GOOGL',
    name: 'Alphabet Inc.',
    price: 135.0,
    change: 0.75,
    changePercentage: 0.56,
    marketCap: '1.8T',
    volume: '40M',
    avgVolume: '50M',
    peRatio: 28.0,
    dividendYield: null,
  },
  {
    symbol: 'AMZN',
    name: 'Amazon.com, Inc.',
    price: 140.0,
    change: 2.5,
    changePercentage: 1.82,
    marketCap: '1.5T',
    volume: '60M',
    avgVolume: '70M',
    peRatio: 60.0,
    dividendYield: null,
  },
  {
    symbol: 'NVDA',
    name: 'NVIDIA Corp.',
    price: 450.0,
    change: -5.0,
    changePercentage: -1.1,
    marketCap: '1.2T',
    volume: '70M',
    avgVolume: '80M',
    peRatio: 95.0,
    dividendYield: 0.1,
  },
  {
    symbol: 'META',
    name: 'Meta Platforms Inc',
    price: 330.0,
    change: 3.5,
    changePercentage: 1.07,
    marketCap: '1.84T',
    volume: '25M',
    avgVolume: '30M',
    peRatio: 26.0,
    dividendYield: null,
  },
  {
    symbol: 'AVGO',
    name: 'Broadcom Inc.',
    price: 800.0,
    change: -10.0,
    changePercentage: -1.23,
    marketCap: '1.55T',
    volume: '5M',
    avgVolume: '7M',
    peRatio: 20.0,
    dividendYield: 1.8,
  },
  {
    symbol: 'TSM',
    name: 'Taiwan Semiconductor Manufacturing Co Ltd',
    price: 130.0,
    change: 2.1,
    changePercentage: 1.64,
    marketCap: '876.86B',
    volume: '15M',
    avgVolume: '20M',
    peRatio: 22.0,
    dividendYield: 1.5,
  },
  {
    symbol: 'ORCL',
    name: 'Oracle Corp',
    price: 120.0,
    change: -1.0,
    changePercentage: -0.83,
    marketCap: '799.20B',
    volume: '10M',
    avgVolume: '12M',
    peRatio: 18.0,
    dividendYield: 2.0,
  },
  {
    symbol: 'PLTR',
    name: 'Palantir Technologies Inc',
    price: 25.0,
    change: 0.5,
    changePercentage: 2.04,
    marketCap: '432.76B',
    volume: '50M',
    avgVolume: '60M',
    peRatio: 150.0,
    dividendYield: null,
  },
  {
    symbol: 'TCEHY',
    name: 'Tencent Holdings Ltd',
    price: 45.0,
    change: 1.0,
    changePercentage: 2.27,
    marketCap: '444.51B',
    volume: '20M',
    avgVolume: '25M',
    peRatio: 20.0,
    dividendYield: 0.5,
  },
  {
    symbol: 'ASML',
    name: 'ASML Holding NV',
    price: 700.0,
    change: -5.0,
    changePercentage: -0.71,
    marketCap: '319.71B',
    volume: '2M',
    avgVolume: '3M',
    peRatio: 40.0,
    dividendYield: 0.7,
  },
  {
    symbol: 'SAMSUNG',
    name: 'Samsung Electronics Co Ltd',
    price: 60.0,
    change: 0.2,
    changePercentage: 0.33,
    marketCap: '319.55B',
    volume: '30M',
    avgVolume: '35M',
    peRatio: 15.0,
    dividendYield: 2.5,
  },
  {
    symbol: 'NFLX',
    name: 'Netflix Inc.',
    price: 420.0,
    change: 8.0,
    changePercentage: 1.94,
    marketCap: '298.91B',
    volume: '8M',
    avgVolume: '10M',
    peRatio: 45.0,
    dividendYield: null,
  },
  {
    symbol: 'SAP',
    name: 'SAP SE',
    price: 150.0,
    change: 1.2,
    changePercentage: 0.81,
    marketCap: '260.82B',
    volume: '4M',
    avgVolume: '5M',
    peRatio: 30.0,
    dividendYield: 1.2,
  },
  {
    symbol: 'AMD',
    name: 'Advanced Micro Devices Inc',
    price: 110.0,
    change: -2.0,
    changePercentage: -1.79,
    marketCap: '246.13B',
    volume: '60M',
    avgVolume: '70M',
    peRatio: 35.0,
    dividendYield: null,
  },
  {
    symbol: 'CRM',
    name: 'Salesforce Inc',
    price: 240.0,
    change: 3.0,
    changePercentage: 1.27,
    marketCap: '245.60B',
    volume: '7M',
    avgVolume: '9M',
    peRatio: 70.0,
    dividendYield: null,
  },
  {
    symbol: 'ADBE',
    name: 'Adobe Inc',
    price: 500.0,
    change: -4.0,
    changePercentage: -0.79,
    marketCap: '231.23B',
    volume: '3M',
    avgVolume: '4M',
    peRatio: 50.0,
    dividendYield: null,
  },
  {
    symbol: 'CSCO',
    name: 'Cisco Systems Inc',
    price: 55.0,
    change: 0.5,
    changePercentage: 0.92,
    marketCap: '203.64B',
    volume: '20M',
    avgVolume: '25M',
    peRatio: 18.0,
    dividendYield: 3.0,
  },
  {
    symbol: 'BABA',
    name: 'Alibaba Group Holding Ltd',
    price: 90.0,
    change: -1.5,
    changePercentage: -1.64,
    marketCap: '201.57B',
    volume: '40M',
    avgVolume: '50M',
    peRatio: 25.0,
    dividendYield: null,
  },
  {
    symbol: 'IBM',
    name: 'International Business Machines Corp',
    price: 140.0,
    change: 1.0,
    changePercentage: 0.72,
    marketCap: '200.03B',
    volume: '5M',
    avgVolume: '6M',
    peRatio: 20.0,
    dividendYield: 4.5,
  },
  {
    symbol: 'QCOM',
    name: 'Qualcomm Inc',
    price: 130.0,
    change: 2.0,
    changePercentage: 1.56,
    marketCap: '185.60B',
    volume: '10M',
    avgVolume: '12M',
    peRatio: 22.0,
    dividendYield: 2.8,
  },
  {
    symbol: 'NOW',
    name: 'ServiceNow Inc',
    price: 600.0,
    change: -8.0,
    changePercentage: -1.32,
    marketCap: '183.71B',
    volume: '2M',
    avgVolume: '3M',
    peRatio: 120.0,
    dividendYield: null,
  },
  {
    symbol: 'TXN',
    name: 'Texas Instruments Inc',
    price: 180.0,
    change: 1.5,
    changePercentage: 0.84,
    marketCap: '181.21B',
    volume: '6M',
    avgVolume: '8M',
    peRatio: 25.0,
    dividendYield: 2.2,
  },
  {
    symbol: 'INTU',
    name: 'Intuit Inc',
    price: 450.0,
    change: 5.0,
    changePercentage: 1.12,
    marketCap: '181.13B',
    volume: '3M',
    avgVolume: '4M',
    peRatio: 60.0,
    dividendYield: 0.8,
  },
  {
    symbol: 'AMAT',
    name: 'Applied Materials Inc',
    price: 140.0,
    change: -2.5,
    changePercentage: -1.75,
    marketCap: '154.64B',
    volume: '8M',
    avgVolume: '10M',
    peRatio: 28.0,
    dividendYield: 1.5,
  },
  {
    symbol: 'UBER',
    name: 'Uber Technologies Inc',
    price: 45.0,
    change: 1.8,
    changePercentage: 4.17,
    marketCap: '150.25B',
    volume: '50M',
    avgVolume: '60M',
    peRatio: null,
    dividendYield: null,
  },
  {
    symbol: 'ARM',
    name: 'Arm Holdings PLC',
    price: 60.0,
    change: -0.5,
    changePercentage: -0.83,
    marketCap: '145.04B',
    volume: '20M',
    avgVolume: '25M',
    peRatio: 100.0,
    dividendYield: null,
  },
  {
    symbol: 'SU',
    name: 'Schneider Electric SE',
    price: 160.0,
    change: 2.0,
    changePercentage: 1.27,
    marketCap: '142.44B',
    volume: '4M',
    avgVolume: '5M',
    peRatio: 24.0,
    dividendYield: 2.0,
  },
  {
    symbol: 'PDD',
    name: 'Pinduoduo (PDD Holdings Inc)',
    price: 100.0,
    change: -3.0,
    changePercentage: -2.91,
    marketCap: '134.98B',
    volume: '30M',
    avgVolume: '40M',
    peRatio: 30.0,
    dividendYield: null,
  },
];

export const TRENDING_STOCKS: Stock[] = [
  {
    symbol: 'TSLA',
    name: 'Tesla, Inc.',
    price: 250.0,
    change: 10.0,
    changePercentage: 4.17,
    marketCap: '800B',
    volume: '120M',
    avgVolume: '100M',
    peRatio: 70.0,
    dividendYield: null,
  },
  {
    symbol: 'META',
    name: 'Meta Platforms, Inc.',
    price: 320.0,
    change: -3.0,
    changePercentage: -0.93,
    marketCap: '900B',
    volume: '30M',
    avgVolume: '40M',
    peRatio: 25.0,
    dividendYield: null,
  },
  {
    symbol: 'NFLX',
    name: 'Netflix, Inc.',
    price: 400.0,
    change: 8.0,
    changePercentage: 2.04,
    marketCap: '180B',
    volume: '20M',
    avgVolume: '25M',
    peRatio: 40.0,
    dividendYield: null,
  },
];

export const USER_PROFILE_STOCKS: Stock[] = [
  {
    symbol: 'AAPL',
    name: 'Apple Inc.',
    price: 175.0,
    change: 1.5,
    changePercentage: 0.86,
    marketCap: '2.8T',
    volume: '80M',
    avgVolume: '100M',
    peRatio: 30.0,
    dividendYield: 0.5,
    amount: 10,
  },
  {
    symbol: 'TSLA',
    name: 'Tesla, Inc.',
    price: 250.0,
    change: 10.0,
    changePercentage: 4.17,
    marketCap: '800B',
    volume: '120M',
    avgVolume: '100M',
    peRatio: 70.0,
    dividendYield: null,
    amount: 5,
  },
];
